using System.Net.Http;
using System.Text;

namespace MandrillSimulator.Services;

// Posts a representative payload at the simulator's own listener so a tester can
// confirm the tool works before wiring an application to it.
public class SampleMessageSender
{
    private static readonly HttpClient Client = new() { Timeout = TimeSpan.FromSeconds(10) };

    public Task SendAsync(string baseUrl) => SendRawAsync(baseUrl, BuildPayload());

    // Replays an exact captured body, which is what the inbox's Resend uses.
    public async Task SendRawAsync(string baseUrl, string payload)
    {
        using var content = new StringContent(payload, Encoding.UTF8, "application/json");

        // Deliberately concatenated the way a caller building "base + /path" does,
        // so this also exercises the double-slash normalisation.
        var url = baseUrl + "/messages/send.json";
        using var response = await Client.PostAsync(url, content).ConfigureAwait(false);
        response.EnsureSuccessStatusCode();
    }

    private static string BuildPayload() =>
        """
        {
          "key": "local-dev-not-a-real-key",
          "message": {
            "subject": "Sample message from the simulator",
            "from_email": "no-reply@example.com",
            "from_name": "Mandrill Simulator",
            "to": [ { "email": "tester@example.com", "name": "Tester", "type": "to" } ],
            "tags": [ "sample" ],
            "track_opens": true,
            "track_clicks": true,
            "html": "<html><body style=\"font-family:Arial,sans-serif\"><h2>It works</h2><p>This message was generated by the simulator itself, so the listener, the store and the inbox are all wired up correctly.</p><p><a href=\"https://example.com/sample-document\">A link you can click to raise the click counter</a></p><p>Best wishes,<br/>Mandrill Simulator</p></body></html>"
          },
          "send_at": ""
        }
        """;
}
